# Generated by Django 6.1.1 on 2026-09-24 07:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.PositiveIntegerField(db_index=True, verbose_name='玩家ID')),
                ('account', models.CharField(blank=True, default='', max_length=64, verbose_name='玩家账号')),
                ('player_name', models.CharField(blank=True, default='', max_length=64, verbose_name='玩家昵称')),
                ('action', models.CharField(choices=[('ban', '封禁'), ('unban', '解封')], max_length=16, verbose_name='操作')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='原因')),
                ('operator_name', models.CharField(blank=True, default='', max_length=150, verbose_name='操作人账号')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='自动解封时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bans', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '玩家封禁记录',
                'verbose_name_plural': '玩家封禁记录',
                'db_table': 'players_playerban',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['player_id', '-created_at'], name='idx_player_ban_time'), models.Index(fields=['action', '-created_at'], name='idx_player_ban_action')],
            },
        ),
    ]
